version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      npm-patch-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions-patch-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
