export enum SupportedNetworkEnum {
    Amex = 'amex',
    Bancontact = 'bancontact',
    CartesBancaires = 'cartesBancaires',
    ChinaUnionPay = 'chinaUnionPay',
    Dankort = 'dankort',
    Discover = 'discover',
    Eftpos = 'eftpos',
    Electron = 'electron',
    Elo = 'elo',
    Girocard = 'girocard',
    Interac = 'interac',
    Jcb = 'jcb',
    Mada = 'mada',
    Maestro = 'maestro',
    Mastercard = 'masterCard',
    Mir = 'mir',
    PrivateLabel = 'privateLabel',
    Visa = 'visa',
    Vpay = 'vPay',
}
