name: PR Closed Cleanup

on:
    pull_request:
        types: [closed]

jobs:
    cleanup:
        permissions:
            # Required to cancel queued and in-progress runs for the closed pull request.
            actions: write
        uses: rnw-community/mobile-ci/.github/workflows/pr-closed-cleanup-reusable.yml@e6360047cd92fbf524d99a7ddc352fa566d3638a # v1.3.0
