name: PR Closed Cleanup

on:
    pull_request:
        types: [closed]

permissions:
    actions: write

jobs:
    cleanup:
        permissions:
            actions: write
        uses: rnw-community/mobile-ci/.github/workflows/pr-closed-cleanup-reusable.yml@bc5927455f3ca5aed5c1b7733c9286fc8b53769e # v1.0.0
