name: PR Closed Cleanup

on:
    pull_request:
        types: [closed]

jobs:
    cleanup:
        permissions:
            actions: write
        uses: rnw-community/mobile-ci/.github/workflows/pr-closed-cleanup-reusable.yml@3ecd0054f64589c063112b73469a492b224bd866 # v1.0.1
