name: Pull Request

env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
    PR_TITLE: ${{ github.event.pull_request.title }}
    YARN_ENABLE_IMMUTABLE_INSTALLS: true

concurrency:
    group: pr-${{ github.event.pull_request.number }}
    cancel-in-progress: true

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    code-quality:
        name: Build, lint and test
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            issues: write
            pull-requests: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v5
                with:
                    fetch-depth: 0

            -   name: Close Stale Issues
                uses: actions/stale@v10

            -   name: Setup Node
                uses: actions/setup-node@v5
                with:
                    node-version: 22.x
                    cache: yarn

            -   name: Enable corepack
                run: corepack enable

            -   name: Install dependencies
                run: yarn install --immutable

            -   name: Lint the PR Title
                run: echo "${{ env.PR_TITLE }}" | node_modules/.bin/commitlint

            -   name: Build packages
                run: yarn turbo run build --affected

            -   name: Typescript checks
                run: yarn turbo run ts --affected

            -   name: ESLint checks
                run: yarn turbo run lint --affected

            -   name: Find dead code
                run: yarn deadcode

            -   name: Find copy-paste
                run: yarn cpd

            -   name: Unit tests
                run: yarn turbo run test:coverage --affected

            -   name: Upload coverage - decorators-core
                if: hashFiles('packages/decorators-core/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/decorators-core/coverage/lcov.info
                    flags: decorators-core

            -   name: Upload coverage - eslint-plugin
                if: hashFiles('packages/eslint-plugin/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/eslint-plugin/coverage/lcov.info
                    flags: eslint-plugin

            -   name: Upload coverage - fast-style
                if: hashFiles('packages/fast-style/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/fast-style/coverage/lcov.info
                    flags: fast-style

            -   name: Upload coverage - histogram-metric-decorator
                if: hashFiles('packages/histogram-metric-decorator/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/histogram-metric-decorator/coverage/lcov.info
                    flags: histogram-metric-decorator

            -   name: Upload coverage - lock-decorator
                if: hashFiles('packages/lock-decorator/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/lock-decorator/coverage/lcov.info
                    flags: lock-decorator

            -   name: Upload coverage - log-decorator
                if: hashFiles('packages/log-decorator/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/log-decorator/coverage/lcov.info
                    flags: log-decorator

            -   name: Upload coverage - nestjs-enterprise
                if: hashFiles('packages/nestjs-enterprise/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/nestjs-enterprise/coverage/lcov.info
                    flags: nestjs-enterprise

            -   name: Upload coverage - nestjs-rxjs-lock
                if: hashFiles('packages/nestjs-rxjs-lock/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/nestjs-rxjs-lock/coverage/lcov.info
                    flags: nestjs-rxjs-lock

            -   name: Upload coverage - nestjs-rxjs-logger
                if: hashFiles('packages/nestjs-rxjs-logger/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/nestjs-rxjs-logger/coverage/lcov.info
                    flags: nestjs-rxjs-logger

            -   name: Upload coverage - nestjs-rxjs-metrics
                if: hashFiles('packages/nestjs-rxjs-metrics/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/nestjs-rxjs-metrics/coverage/lcov.info
                    flags: nestjs-rxjs-metrics

            -   name: Upload coverage - nestjs-rxjs-redis
                if: hashFiles('packages/nestjs-rxjs-redis/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/nestjs-rxjs-redis/coverage/lcov.info
                    flags: nestjs-rxjs-redis

            -   name: Upload coverage - nestjs-typed-config
                if: hashFiles('packages/nestjs-typed-config/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/nestjs-typed-config/coverage/lcov.info
                    flags: nestjs-typed-config

            -   name: Upload coverage - object-field-tree
                if: hashFiles('packages/object-field-tree/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/object-field-tree/coverage/lcov.info
                    flags: object-field-tree

            -   name: Upload coverage - platform
                if: hashFiles('packages/platform/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/platform/coverage/lcov.info
                    flags: platform

            -   name: Upload coverage - react-native-payments
                if: hashFiles('packages/react-native-payments/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/react-native-payments/coverage/lcov.info
                    flags: react-native-payments

            -   name: Upload coverage - redux-loadable
                if: hashFiles('packages/redux-loadable/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/redux-loadable/coverage/lcov.info
                    flags: redux-loadable

            -   name: Upload coverage - rxjs-errors
                if: hashFiles('packages/rxjs-errors/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/rxjs-errors/coverage/lcov.info
                    flags: rxjs-errors

            -   name: Upload coverage - shared
                if: hashFiles('packages/shared/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/shared/coverage/lcov.info
                    flags: shared

            -   name: Upload coverage - wdio
                if: hashFiles('packages/wdio/coverage/lcov.info') != ''
                uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
                with:
                    use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    fail_ci_if_error: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
                    files: packages/wdio/coverage/lcov.info
                    flags: wdio

    required-checks:
        name: Required checks
        if: always()
        needs: [code-quality]
        timeout-minutes: 5
        runs-on: ubuntu-latest
        permissions: {}

        steps:
            -   name: Verify required jobs succeeded
                env:
                    CODE_QUALITY_RESULT: ${{ needs.code-quality.result }}
                run: |
                    echo "code-quality=${CODE_QUALITY_RESULT}"
                    if [ "${CODE_QUALITY_RESULT}" != 'success' ]; then
                      echo "Required jobs did not pass"
                      exit 1
                    fi
